[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
from = "https://hd.magnolia-cms.com/docs/introduction"
to = "https://docs.magnolia-cms.com/headless/index.html"
status = 301
force = false

[[redirects]]
from = "https://hd.magnolia-cms.com/docs/getting-started/start"
to = "https://docs.magnolia-cms.com/headless/getting-started/start.html"
status = 301
force = false

[[redirects]]
from = "https://hd.magnolia-cms.com/docs/getting-started/installation"
to = "https://docs.magnolia-cms.com/headless/getting-started/installation.html"
status = 301
force = false

[[redirects]]
from = "https://hd.magnolia-cms.com/docs/getting-started/hello-headless"
to = "https://docs.magnolia-cms.com/headless/getting-started/hello-headless.html"
status = 301
force = false

[[redirects]]
from = "https://hd.magnolia-cms.com/docs/getting-started/hello-spa"
to = "https://docs.magnolia-cms.com/headless/getting-started/hello-spa.html"
status = 301
force = false

[[redirects]]
from = "https://hd.magnolia-cms.com/docs/concepts/light-development"
to = "https://docs.magnolia-cms.com/headless/concepts/light-development.html"
status = 301
force = false

[[redirects]]
from = "https://hd.magnolia-cms.com/docs/concepts/yaml-hyper-config"
to = "https://docs.magnolia-cms.com/headless/concepts/yaml-hyper-config.html"
status = 301
force = false

[[redirects]]
from = "https://hd.magnolia-cms.com/docs/concepts/content-modelling"
to = "https://docs.magnolia-cms.com/headless/concepts/content-modelling.html"
status = 301
force = false

[[redirects]]
from = "https://hd.magnolia-cms.com/docs/concepts/templating"
to = "https://docs.magnolia-cms.com/headless/concepts/templating.html"
status = 301
force = false

[[redirects]]
from = "https://hd.magnolia-cms.com/docs/concepts/customization"
to = "https://docs.magnolia-cms.com/headless/concepts/customization.html"
status = 301
force = false

[[redirects]]
from = "https://hd.magnolia-cms.com/docs/concepts/integration"
to = "https://docs.magnolia-cms.com/headless/concepts/integration.html"
status = 301
force = false

[[redirects]]
from = "https://hd.magnolia-cms.com/docs/visual-spa-editor"
to = "https://docs.magnolia-cms.com/headless/visual-spa-editor.html"
status = 301
force = false

[[redirects]]
from = "https://hd.magnolia-cms.com/docs/jamstack"
to = "https://docs.magnolia-cms.com/headless/jamstack.html"
status = 301
force = false

[[redirects]]
from = "https://hd.magnolia-cms.com/docs/content-types"
to = "https://docs.magnolia-cms.com/headless/content-types.html"
status = 301
force = false

[[redirects]]
from = "https://hd.magnolia-cms.com/docs/api/delivery"
to = "https://docs.magnolia-cms.com/headless/api/delivery.html"
status = 301
force = false

[[redirects]]
from = "/api-explorer"
to = "https://docs.magnolia-cms.com/headless/api/delivery/explorer.html"
status = 301
force = false

[[redirects]]
from = "https://hd.magnolia-cms.com/docs/api/management"
to = "https://docs.magnolia-cms.com/headless/api/management.html"
status = 301
force = false
